"""add_channel_fields_to_task

Revision ID: 089dc0c370a9
Revises: 2617fd1f6687
Create Date: 2026-03-30 10:12:54.187552

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "089dc0c370a9"
down_revision: Union[str, None] = "2617fd1f6687"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [col["name"] for col in inspector.get_columns("tasks")]

    if "channel_id" not in columns:
        op.add_column("tasks", sa.Column("channel_id", sa.Integer(), nullable=True))
    if "channel_name" not in columns:
        op.add_column(
            "tasks", sa.Column("channel_name", sa.String(length=100), nullable=True)
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [col["name"] for col in inspector.get_columns("tasks")]

    if "channel_name" in columns:
        op.drop_column("tasks", "channel_name")
    if "channel_id" in columns:
        op.drop_column("tasks", "channel_id")
    # ### end Alembic commands ###
