"""Add UserChannel model

Revision ID: 2617fd1f6687
Revises: 46f7cf93d814
Create Date: 2026-03-27 18:33:17.381576

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "2617fd1f6687"
down_revision: Union[str, None] = "46f7cf93d814"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
