"""Add UserChannel

Revision ID: 46f7cf93d814
Revises: 62ee04b26702
Create Date: 2026-03-27 18:24:43.001005

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "46f7cf93d814"
down_revision: Union[str, None] = "62ee04b26702"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()

    if "user_channels" not in existing_tables:
        # Build foreign key constraints dynamically based on what tables exist
        # This handles running migrations from empty database
        foreign_keys = []

        # Only add user_id FK if users table exists
        if "users" in existing_tables:
            foreign_keys.append(
                sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE")
            )

        op.create_table(
            "user_channels",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("user_id", sa.Integer(), nullable=False),
            sa.Column("channel_type", sa.String(length=50), nullable=False),
            sa.Column("channel_name", sa.String(length=100), nullable=False),
            sa.Column("config", sa.JSON(), nullable=False),
            sa.Column("is_active", sa.Boolean(), nullable=False),
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("CURRENT_TIMESTAMP"),
                nullable=True,
            ),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            *foreign_keys,
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(
            op.f("ix_user_channels_id"), "user_channels", ["id"], unique=False
        )

    if "user_telegram_bots" in existing_tables:
        op.drop_index(op.f("ix_user_telegram_bots_id"), table_name="user_telegram_bots")
        op.drop_table("user_telegram_bots")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()

    if "user_telegram_bots" not in existing_tables:
        # Build foreign key constraints dynamically based on what tables exist
        foreign_keys = []
        if "users" in existing_tables:
            foreign_keys.append(
                sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE")
            )

        op.create_table(
            "user_telegram_bots",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("user_id", sa.Integer(), nullable=False),
            sa.Column("bot_token", sa.String(length=255), nullable=False),
            sa.Column("bot_name", sa.String(length=255), nullable=True),
            sa.Column("is_active", sa.Boolean(), nullable=False),
            sa.Column(
                "created_at",
                sa.DateTime(),
                server_default=sa.text("CURRENT_TIMESTAMP"),
                nullable=True,
            ),
            sa.Column("updated_at", sa.DateTime(), nullable=True),
            *foreign_keys,
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("user_id"),
        )
        op.create_index(
            op.f("ix_user_telegram_bots_id"), "user_telegram_bots", ["id"], unique=False
        )

    if "user_channels" in existing_tables:
        op.drop_index(op.f("ix_user_channels_id"), table_name="user_channels")
        op.drop_table("user_channels")
    # ### end Alembic commands ###
