"""add_foreign_key_to_task_channel_id

Revision ID: 7f6d2ffea948
Revises: 089dc0c370a9
Create Date: 2026-03-30 10:16:43.162662

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7f6d2ffea948"
down_revision: Union[str, None] = "089dc0c370a9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    fks = inspector.get_foreign_keys("tasks")
    fk_names = [fk["name"] for fk in fks]

    if "fk_tasks_channel_id" not in fk_names:
        with op.batch_alter_table("tasks") as batch_op:
            batch_op.create_foreign_key(
                "fk_tasks_channel_id",
                "user_channels",
                ["channel_id"],
                ["id"],
                ondelete="SET NULL",
            )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    fks = inspector.get_foreign_keys("tasks")
    fk_names = [fk["name"] for fk in fks]

    if "fk_tasks_channel_id" in fk_names:
        with op.batch_alter_table("tasks") as batch_op:
            batch_op.drop_constraint("fk_tasks_channel_id", type_="foreignkey")
    # ### end Alembic commands ###
