"""Add OAuthProvider and PublicMCPApp tables

Revision ID: f1427c3a7261
Revises: 002_update_agent_execution_mode
Create Date: 2026-04-21 15:53:38.321174

"""

import os
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f1427c3a7261"
down_revision: Union[str, None] = "002_update_agent_execution_mode"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from alembic import context
    from sqlalchemy import inspect, text

    bind = context.get_bind()
    inspector = inspect(bind)
    existing_tables = inspector.get_table_names()

    if "oauth_providers" not in existing_tables:
        op.create_table(
            "oauth_providers",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("provider_name", sa.String(length=50), nullable=False),
            sa.Column("name", sa.String(length=100), nullable=False),
            sa.Column("client_id", sa.String(length=500), nullable=False),
            sa.Column("client_secret", sa.String(length=500), nullable=False),
            sa.Column("auth_url", sa.String(length=1000), nullable=False),
            sa.Column("token_url", sa.String(length=1000), nullable=False),
            sa.Column("redirect_uri", sa.String(length=1000), nullable=True),
            sa.Column("userinfo_url", sa.String(length=1000), nullable=True),
            sa.Column("user_id_path", sa.String(length=100), nullable=True),
            sa.Column("email_path", sa.String(length=100), nullable=True),
            sa.Column("default_scopes", sa.JSON(), nullable=True),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(
            op.f("ix_oauth_providers_id"), "oauth_providers", ["id"], unique=False
        )
        op.create_index(
            op.f("ix_oauth_providers_provider_name"),
            "oauth_providers",
            ["provider_name"],
            unique=True,
        )
    if "public_mcp_apps" not in existing_tables:
        op.create_table(
            "public_mcp_apps",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("app_id", sa.String(length=100), nullable=False),
            sa.Column("name", sa.String(length=200), nullable=False),
            sa.Column("description", sa.Text(), nullable=True),
            sa.Column("icon", sa.String(length=1000), nullable=True),
            sa.Column("transport", sa.String(length=50), nullable=False),
            sa.Column("provider_name", sa.String(length=50), nullable=True),
            sa.Column("category", sa.String(length=100), nullable=True),
            sa.Column("oauth_scopes", sa.JSON(), nullable=True),
            sa.Column("launch_config", sa.JSON(), nullable=True),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(
            op.f("ix_public_mcp_apps_app_id"),
            "public_mcp_apps",
            ["app_id"],
            unique=True,
        )
        op.create_index(
            op.f("ix_public_mcp_apps_id"), "public_mcp_apps", ["id"], unique=False
        )
    # op.drop_index(op.f('ix_uploaded_files_filename'), table_name='uploaded_files')

    # Try to load dotenv manually for this context if .env is present
    try:
        from dotenv import load_dotenv

        load_dotenv(os.path.join(os.getcwd(), ".env"))
    except Exception:
        pass

    # Insert default data, reading from env if present
    oauth_providers_table = sa.table(
        "oauth_providers",
        sa.column("provider_name", sa.String),
        sa.column("name", sa.String),
        sa.column("client_id", sa.String),
        sa.column("client_secret", sa.String),
        sa.column("auth_url", sa.String),
        sa.column("token_url", sa.String),
        sa.column("redirect_uri", sa.String),
        sa.column("userinfo_url", sa.String),
        sa.column("user_id_path", sa.String),
        sa.column("email_path", sa.String),
        sa.column("default_scopes", sa.JSON),
    )

    existing_provider_names: set[str] = set()
    if "oauth_providers" in inspector.get_table_names():
        existing_provider_names = {
            row[0]
            for row in bind.execute(
                text("SELECT provider_name FROM oauth_providers")
            ).fetchall()
        }

    oauth_provider_rows = [
        {
            "provider_name": "google",
            "name": "Google",
            "client_id": os.environ.get("GOOGLE_CLIENT_ID", ""),
            "client_secret": os.environ.get("GOOGLE_CLIENT_SECRET", ""),
            "auth_url": "https://accounts.google.com/o/oauth2/auth",
            "token_url": "https://oauth2.googleapis.com/token",
            "redirect_uri": os.environ.get("GOOGLE_REDIRECT_URI", ""),
            "userinfo_url": "https://www.googleapis.com/oauth2/v2/userinfo",
            "user_id_path": "id",
            "email_path": "email",
            "default_scopes": [
                "https://www.googleapis.com/auth/userinfo.email",
                "https://www.googleapis.com/auth/userinfo.profile",
            ],
        },
        {
            "provider_name": "linkedin",
            "name": "LinkedIn",
            "client_id": os.environ.get("LINKEDIN_CLIENT_ID", ""),
            "client_secret": os.environ.get("LINKEDIN_CLIENT_SECRET", ""),
            "auth_url": "https://www.linkedin.com/oauth/v2/authorization",
            "token_url": "https://www.linkedin.com/oauth/v2/accessToken",
            "redirect_uri": os.environ.get("LINKEDIN_REDIRECT_URI", ""),
            "userinfo_url": "https://api.linkedin.com/v2/userinfo",
            "user_id_path": "sub",
            "email_path": "email",
            "default_scopes": ["openid", "profile", "email", "w_member_social"],
        },
    ]
    oauth_provider_rows_to_insert = [
        row
        for row in oauth_provider_rows
        if row["provider_name"] not in existing_provider_names
    ]
    if oauth_provider_rows_to_insert:
        op.bulk_insert(oauth_providers_table, oauth_provider_rows_to_insert)

    public_mcp_apps_table = sa.table(
        "public_mcp_apps",
        sa.column("app_id", sa.String),
        sa.column("name", sa.String),
        sa.column("description", sa.Text),
        sa.column("icon", sa.String),
        sa.column("transport", sa.String),
        sa.column("provider_name", sa.String),
        sa.column("category", sa.String),
        sa.column("oauth_scopes", sa.JSON),
        sa.column("launch_config", sa.JSON),
    )

    existing_app_ids: set[str] = set()
    if "public_mcp_apps" in inspector.get_table_names():
        existing_app_ids = {
            row[0]
            for row in bind.execute(
                text("SELECT app_id FROM public_mcp_apps")
            ).fetchall()
        }

    public_mcp_app_rows = [
        {
            "app_id": "linkedin",
            "name": "LinkedIn",
            "description": "Access LinkedIn to retrieve basic user profiles and manage your created posts.",
            "icon": "https://www.google.com/s2/favicons?domain=linkedin.com&sz=128",
            "transport": "oauth",
            "provider_name": "linkedin",
            "category": "CRM",
            "oauth_scopes": ["openid", "profile", "email", "w_member_social"],
            "launch_config": {
                "command": "uv",
                "args": ["run", "python", "-m", "xagent.web.tools.mcp.linkedin"],
                "env_mapping": {"LINKEDIN_ACCESS_TOKEN": "access_token"},
            },
        },
        {
            "app_id": "gmail",
            "name": "Gmail",
            "description": "Connect to your Gmail inbox to read, search, draft, and send emails.",
            "icon": "https://www.google.com/s2/favicons?domain=mail.google.com&sz=128",
            "transport": "oauth",
            "provider_name": "google",
            "category": "Communication",
            "oauth_scopes": ["https://www.googleapis.com/auth/gmail.modify"],
            "launch_config": {
                "command": "uv",
                "args": ["run", "python", "-m", "xagent.web.tools.mcp.gmail"],
                "env_mapping": {"GOOGLE_ACCESS_TOKEN": "access_token"},
            },
        },
        {
            "app_id": "google-drive",
            "name": "Google Drive",
            "description": "Access Google Drive to search for files, read documents, and manage your cloud storage.",
            "icon": "https://www.google.com/s2/favicons?domain=drive.google.com&sz=128",
            "transport": "oauth",
            "provider_name": "google",
            "category": "Support",
            "oauth_scopes": ["https://www.googleapis.com/auth/drive"],
            "launch_config": {
                "command": "uv",
                "args": [
                    "run",
                    "python",
                    "-m",
                    "xagent.web.tools.mcp.google_drive",
                ],
                "env_mapping": {"GOOGLE_ACCESS_TOKEN": "access_token"},
            },
        },
        {
            "app_id": "google-calendar",
            "name": "Google Calendar",
            "description": "Connect to Google Calendar to manage events, schedule meetings, and view your daily agenda.",
            "icon": "https://www.google.com/s2/favicons?domain=calendar.google.com&sz=128",
            "transport": "oauth",
            "provider_name": "google",
            "category": "Scheduling",
            "oauth_scopes": ["https://www.googleapis.com/auth/calendar"],
            "launch_config": {
                "command": "uv",
                "args": ["run", "python", "-m", "xagent.web.tools.mcp.calendar"],
                "env_mapping": {"GOOGLE_ACCESS_TOKEN": "access_token"},
            },
        },
    ]
    public_mcp_app_rows_to_insert = [
        row for row in public_mcp_app_rows if row["app_id"] not in existing_app_ids
    ]
    if public_mcp_app_rows_to_insert:
        op.bulk_insert(public_mcp_apps_table, public_mcp_app_rows_to_insert)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from alembic import context
    from sqlalchemy import inspect

    bind = context.get_bind()
    inspector = inspect(bind)
    existing_tables = set(inspector.get_table_names())

    if "public_mcp_apps" in existing_tables:
        existing_indexes = {
            idx["name"] for idx in inspector.get_indexes("public_mcp_apps")
        }
        for idx_name in [
            op.f("ix_public_mcp_apps_id"),
            op.f("ix_public_mcp_apps_app_id"),
        ]:
            if idx_name in existing_indexes:
                op.drop_index(idx_name, table_name="public_mcp_apps")
        op.drop_table("public_mcp_apps")

    if "oauth_providers" in existing_tables:
        existing_indexes = {
            idx["name"] for idx in inspector.get_indexes("oauth_providers")
        }
        for idx_name in [
            op.f("ix_oauth_providers_provider_name"),
            op.f("ix_oauth_providers_id"),
        ]:
            if idx_name in existing_indexes:
                op.drop_index(idx_name, table_name="oauth_providers")
        op.drop_table("oauth_providers")
    # ### end Alembic commands ###
